### ISSUE TITLE
Don't require "Main feed" click on video URLs with only 1 feed

### ISSUE THREAD

**Issue by NewsGuyTor** [najdek/f1tv_plus#1]
Thanks, sweet userscript! It's so damn awesome to not have to dig through the dev tools to find the video URL.

One thing though, it's slightly annoying to have to click on "Main feed" even though it's the only feed. Would be cool if it could show the URL directly for videos with just one feed.

**Comment by najdek** [comment]
Thanks for suggestion.
I'll update it later to use "Main feed" automatically if there's no additional streams.

**Comment by NewsGuyTor** [comment]
I just noticed that the same applies to the alternate player popup.

**Comment by najdek** [comment]
Implemented https://github.com/najdek/f1tv_plus/commit/75593145c67c8ad894bcff9e6071a065a373b5f5
