### ISSUE TITLE
Change header font to the official font

### ISSUE THREAD

**Issue by NewsGuyTor** [najdek/f1tv_plus#10]
The header should use the official Formula 1 font that is used on the links.

The font-family is "Formula1-Regular".

Also related:
#9

**Comment by NewsGuyTor** [comment]
I just tried it (and the color change), it looks good! 👍 

<img width="1202" alt="Skjermbilde 2021-09-12 kl  04 01 38" src="https://user-images.githubusercontent.com/19603024/132968132-388fd914-e3c8-480f-b455-afc13482c2f3.png">

**Comment by NewsGuyTor** [comment]
On the logos and the F1TV+ text, Formula1-Bold looks even better.

**Comment by NewsGuyTor** [comment]
BTW (I won't bother creating a new issue for this), but the feed selection menu above looks much nicer with a `rgba(0, 0, 0, 0.65)` slightly transparent background color.

**Comment by najdek** [comment]
Implemented
https://github.com/najdek/f1tv_plus/commit/cb3e1226e8746464379ef1e2e82987cd0a6145c3
