### ISSUE TITLE
Unselectable drivers on small screen

### ISSUE THREAD

**Issue by mrsnut** [najdek/f1tv_plus#12]
Im using the Tampermonkey addon on my Chrome OS Tablet so I can be and feel like a TV director using the touch screen to select drivers' views and switching to full screen World on my TV (through HDMI) but some drivers are hidden because of the small screen.
Could you make the channel selection view scrollable or make the buttons smaller/less margin?
Even cooler would be for those controls to be able to pop out (while in Frame View) so I could have the frame view on my TV and the controls on my (touch screen) tablet!

![Screenshot 2021-09-24 12 59 13](https://user-images.githubusercontent.com/10139932/134664413-9344fcc6-5078-452d-bf79-c32a9a2847ef.png)

**Comment by najdek** [comment]
I've made the buttons slightly smaller and with less margin.
Also changed default font back to Arial.
Should look better now.
