### ISSUE TITLE
Multi view frames do not work in firefox.

### ISSUE THREAD

**Issue by TheDevFreak** [najdek/f1tv_plus#15]
Only the first frame will function in Firefox browsers, works fine in chrome.

**Comment by najdek** [comment]
Everything works fine for me in Firefox (just tested on Windows and on Android).
Make sure you are using this extension: https://addons.mozilla.org/en-US/firefox/addon/tampermonkey/

**Comment by TheDevFreak** [comment]
Ah yeah, my bad I was using greasemonkey. Works great now.
