### ISSUE TITLE
No livestream since yesterday. 

### ISSUE THREAD

**Issue by daniec1610** [najdek/f1tv_plus#16]
Hi, so far I've used 2 different computers to watch the live sessions of FP2 and now waiting for FP3 to start but the F1TV+ videoplayer never loads no matter how much I wait. 

I've had to disable the script so I can watch it through the standard F1 TV player. This is only a problem with live session not loading as all other content has loaded and played without issues.

**Comment by najdek** [comment]
I think latest Chrome update broke something. I'm having this issue as well, on Chrome 96.0.4664.45
Everything works fine on Edge 96.0.1054.43, and Firefox.

Will look more into this later. For now, I recommend to use another browser.

**Comment by fazlee712** [comment]
yeah same here on Version 97.0.4692.20 (Official Build) beta (64-bit) for what it's worth

**Comment by najdek** [comment]
So, the reason for this issue, is that F1TV is now streaming over DASH protocol on Chrome/Windows.
It's still serving HLS streams on other browsers.

F1TV+ player currently supports only HLS.

### Temporary workaround for this issue:
- use some extension to switch user-agent to any other browser (Chrome/Linux, Chrome/Android, Edge, Firefox).
Like this one: https://chrome.google.com/webstore/detail/user-agent-switcher-and-m/bhchdcejhohfmigjafbampogmaanbfkg/


I'll probably add support for DASH streams, but can't promise if I'll do this before the last race of this season.

**Comment by daniec1610** [comment]
I installed the extension on edge and it works perfectly. chrome still has issues loading up the livestream. CTried it with the F2 feature race and no issues on edge. 

Thank you for your response.

**Comment by najdek** [comment]
Fixed in latest update.
