### ISSUE TITLE
F1TV+ not syncing anymore. Feeds play independently and feed #1 does not control other feeds anymore. Tested on both Chrome and Firefox on both Win10 and Mac OS 12.2.1

### ISSUE THREAD

**Issue by salehesteki** [najdek/f1tv_plus#17]

**Comment by najdek** [comment]
Everything works fine here. Tested on Chrome, Firefox, Edge.
Make sure you are using Tampermonkey extension to load the script.

**Comment by xantrk** [comment]
![image](https://user-images.githubusercontent.com/1756795/164911758-78218a7d-f9e2-4d15-a0cc-69827b143b93.png)
Here it happened to me too

**Comment by xantrk** [comment]
This was a  1big and 5 small screens with 6 in total (frame) had issues.
Some frames worked fine, no idea if it is a frame bug or what

**Comment by najdek** [comment]
> This was a 1big and 5 small screens with 6 in total (frame) had issues. Some frames worked fine, no idea if it is a frame bug or what

Syncing works only when all opened windows are fully loaded and playing.
If one window/frame will crash (e.g. because of not enough memory), syncing will stop, and you'll have to reload everything.
