### ISSUE TITLE
Offsets to sync? 

### ISSUE THREAD

**Issue by zierbeek** [najdek/f1tv_plus#19]
Hi all! what Are the offsets that you use to keep all of them synced to the main feed? 

EDIT: I've found there are some offsets already in the code. Can they be added automatically to the stream or have they to be added manually each time?

**Comment by NewsGuyTor** [comment]
You can see the offsets for most of the 2021 season here, you'd have to create new ones for new races:

https://github.com/najdek/f1tv_plus/blob/master/sync_offsets.json

**Comment by zierbeek** [comment]
yeah sure, I know there are some indeed but quite limited.. questioning if someone has a longer list, personally

**Comment by NewsGuyTor** [comment]
No, we'd collectively need to make them.
