### ISSUE TITLE
Allow seeking in video with arrow keys

### ISSUE THREAD

**Issue by NewsGuyTor** [najdek/f1tv_plus#2]
I'm not sure if this is within scope, I hope it is.

I often find in quite annoying that you can't skip backwards and forwards with the left-right arrow keys on the video player on F1TV, unlike basically all other video sites. 

It would be cool if this userscript could enable seeking on the video player (I'm aware that the alt mode video player has skipping, but that has its own disadvantages).

**Comment by najdek** [comment]
Seeking in default player (Bitmovin) is problematic.
If you'll skip too much, the video freezes and you have to click on the seekbar for it to resume.

I was trying to do this by setting video element's currentTime. 
Maybe someone will find another way to seek video in this player.

That's the main reason I've decided to use default HTML5 player in multi-popout (synchronized mode).
