### ISSUE TITLE
FEATURE: Quickly swap two frame feeds

### ISSUE THREAD

**Issue by LennardF1989** [najdek/f1tv_plus#20]
At first, lovely bit of engineering. I was about to make something similar myself, then Tampermonkey came up with this. Nice! Will see where I can contribute changes by PRs :)

A feature I would like to see is to quickly swap a whole feed configuration.

Eg. I choose this feed:
![image](https://user-images.githubusercontent.com/869973/159123929-accfb971-8eb3-43e5-a000-3d425b703f37.png)

Now, most of the time, the data feed is somewhat small to read, but you can get the gist of it. However, sometimes when things get intense, it will be nice to swap it over to the big screen, and swap the big screen to where data-feed was.

There are a few ways to handle this:
- Add a button to a frame which swaps that feed with the main feed (the script refers to this as the Window 1)
- Add a button to a frame which allows you to swap it with any other frame.
- Add a button to "swap", which remembers the current frame selected. Then click "swap" on another frame to swap the two.
- Allow someone to store the current configuration of the window to a profile and then let users switch between profiles.

Out of all options, I think the first one is the least amount of work, followed by the second one. The third is most likely the most flexible solution (and my preferred one to be honest).

Additional features to make the second one more feasible:
- Add a "frame number" to each frame, so you know which one is 2 or 5.

**Comment by zierbeek** [comment]
hi Lennard! how do you manage the offsets?

**Comment by LennardF1989** [comment]
> hi Lennard! how do you manage the offsets?
Not, I just accept that they are not fully in sync. You can adjust them using the offset menu in the top-left, but way too much hassle, also given it seems to be tied to the Window #, not the feed it's playing.

**Comment by najdek** [comment]
Latest update broke this feature so I had to temporary disable it. I'll try to fix it later.

**Comment by najdek** [comment]
New update has reworked popout mode.
It doesn't look like viewing multiple frames in single window is possible anymore.
