### ISSUE TITLE
FEATURE: Switch multi-view mode at any time

### ISSUE THREAD

**Issue by LennardF1989** [najdek/f1tv_plus#21]
After loading a particular multi-view mode (particularly when using frames), you cannot switch to a new mode without going back one page, selecting a new mode and then reconfigure the frames again.

It would be nice to always have the option to switch between multi-view modes, while at the same time remembering which feeds where selected for each window. 

So if I would go from the 6-screen mode to the 8-screen mode: Window 1 to 6 will show whatever I had selected before, but the two new screen would be blank.

If I would go from the 6-screen mode to the 3 screen mode: Window 1 to 3 will show whatever I had selected before, but I will lose Window 4 to 6.

**Comment by najdek** [comment]
New update has reworked popout mode.
It doesn't look like viewing multiple frames in single window is possible anymore.
