### ISSUE TITLE
Tracker & Data feed issues only when live streaming

### ISSUE THREAD

**Issue by jakobsundin** [najdek/f1tv_plus#22]
Hi there! Absolutely loving this so far. 

Only noticed one weird thing: when live streaming, I cannot seem to get the Tracker or Data view working in Window 1 neither as a sole feed nor in multi-view. It just stays on the F1TV+ logo no matter how long I wait and pauses all the other feeds (if I have any running). They work just fine when running the Main feed or Pit lane in Window 1 and Tracker or Data in any of the other windows.

Weirdly, I only encountered this issue when live streaming the sessions this past weekend. Watching the replays now, both the Tracker and Data feeds work just fine in Window 1.

I've only tested this in Chrome so far, will try Edge & Firefox this upcoming weekend and see how that works.

Appreciate all the hard work on this userscript!

**Comment by najdek** [comment]
Sync mode in live streams is a bit bugged since they started using DASH protocol for live streams.
Unfortunately, I can't really test anything when there's no live stream. 🙄
I'll try to fix this on Friday and if i don't find a solution, I'll just disable window syncing in live streams.

**Comment by jakobsundin** [comment]
I see, well I really appreciate you trying at least! Not the biggest issue in the world if the main feed has to run for the others to work properly, especially now that you can move window 1 to one of the smaller spots in multi-view! :)

**Comment by najdek** [comment]
Latest update switches to default F1TV player, which probably fixes this issue.
