### ISSUE TITLE
seek bar timing issue 

### ISSUE THREAD

**Issue by Siurczek** [najdek/f1tv_plus#23]
![asdadsads](https://user-images.githubusercontent.com/65664067/160139512-23aa7298-8677-4d6c-b9ce-525a4fcf6517.png)
Google chrome v99.0.4844.82
F1TV+ v2.2.7
Timing seems to be the other way around and also hiting right arrow key makes stream go back and forward

**Comment by najdek** [comment]
Should be fixed in latest update.
