### ISSUE TITLE
[FEATURE REQUEST] database to sync all sessions

### ISSUE THREAD

**Issue by MiSeRy81** [najdek/f1tv_plus#25]
Hi.

Is it possible to add an online database to add/change these database to sync all sessions?
And then i start a session and all feeds are synchronized.

That would be great.

**Comment by najdek** [comment]
Hello,
it already exists - sync offsets are automatically loaded from this file:
https://github.com/najdek/f1tv_plus/blob/master/sync_offsets.json

I've added offsets only for first few races of 2021.
I'll be adding new offsets soon (especially for 2022 races).
Of course, anyone can create the offsets and make a pull request.
