### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by retraenn** [najdek/f1tv_plus#26]
No content is loading when using the F1TV+ extension. Getting 403 response when I look at the network tab in console.
Looks like F1TV changed something since other third party viewers are broken today.

**Comment by Aklyn5up** [comment]
Getting the same error, I can't watch anything live, I can however watch replays, but not the latest practice session.

**Comment by luxgertalot** [comment]
Same here. F1 tv Pro subscriber here, logged in. Clicked on the Aussie GP Free Practice 1 link. Tampermonkey shows script being active.

The basic screen loads, with F1TV+, the f1tv+ player, feed selector, etc, but no video is loading.

Opening the inspector shows the following:

Name|Status|Type|Initiator|Size|Time
-- | -- | -- | -- | -- | --
GETSTATICTEXT/ | 304 | document | Other | 297 B | 44 ms
favicon.ico | 301 | text/plain / Redirect | Other | (disk cache) | 2 ms
favicon.ico | 200 | x-icon | favicon.ico | (disk cache) | 3 ms
2 | 200 | xhr | userscript.html?name=F1TV%252B.user.js&id=6076173a-9295-4d64-8db4-10431847506f:3 | (disk cache) | 2 ms
PLAY?contentId=1000005126 | 200 | xhr | userscript.html?name=F1TV%252B.user.js&id=6076173a-9295-4d64-8db4-10431847506f:3 | 2.8 kB | 310 ms
index.mpd?kid=1042&exp=1649480319&ttl=1440&token=e…URwsiS3jD5eM0P6M_&start=1649386504&end=1649390858 | 403 | fetch | userscript.html?name=F1TV%252B.user.js&id=6076173a-9295-4d64-8db4-10431847506f:723 | 0 B | 316 ms
index.mpd?kid=1042&exp=1649480319&ttl=1440&token=e…URwsiS3jD5eM0P6M_&start=1649386504&end=1649390858 | 403 | fetch | userscript.html?name=F1TV%252B.user.js&id=6076173a-9295-4d64-8db4-10431847506f:723 | 0 B | 315 ms

**Comment by najdek** [comment]
Looks like they started using DRM for new streams.
Currently I don't see any way to work around that.

**Comment by Aklyn5up** [comment]
> Looks like they started using DRM for new streams. Currently I don't see any way to work around that.

Well that's a shame, the only reason I got F1TV was for multiple screens, I'll probably go back on the high seas once my subscription is over. Many thanks for the script anyway, it was great while it lasted.

**Comment by luxgertalot** [comment]
> Looks like they started using DRM for new streams. Currently I don't see any way to work around that.

That's a shame. I can open two Chrome windows and watch two feeds that way. I'm trying to work out how to hide every part of the page apart from the video player and controls, and set the size to the full size of the window.

Unfortunately my CSS and DOM skills are very rusty, so I'm not quite there yet.

Would it be an idea to have a tampermonkey script that just hides all the cruft and sets the video to the window's full size? That way I could just open a bunch of windows and select the feeds I want from them. You wouldn't have the syncing, but it's better than the default player.

I know that changes the scope of what you're doing and you may not be interested in going in that direction though, but it's just an idea. I'll keep playing with that for a bit.

**Comment by najdek** [comment]
> Would it be an idea to have a tampermonkey script that just hides all the cruft and sets the video to the window's full size? That way I could just open a bunch of windows and select the feeds I want from them. You wouldn't have the syncing, but it's better than the default player.

That's the first thing I did when I created this script 😉
You can get the old version here:
https://github.com/najdek/f1tv_plus/raw/v1/f1tv_plus.user.js

**Comment by luxgertalot** [comment]
> That's the first thing I did when I created this script 😉

Ha, great minds think alike! I spent a few hours refreshing my memory and ended up with a couple of lines of code in a UserScript that just moves the `embedded-player-container` node to the top and deletes the `#app` with all the cruft.

It works perfectly for one window, which isn't nearly as convenient as your mechanism to set up multiple pop out windows, but it does the trick for now.
