### ISSUE TITLE
Possible sync menu improvements

### ISSUE THREAD

**Issue by Petarkco** [najdek/f1tv_plus#27]
It would be nice to allow the sync menu to be draggable as well as a way to identify which window is which when adjust sync timing.

Also would it be possible to be able to save a sync preset (in case you want to return to a race or to use in other sessions were the feed timing may be the same)?

**Comment by RaJeronimo** [comment]
Most of the races in my experience the sync is different from the main live broadcast to all other channels like drivers, data and position. 6 seconds most of the time. Could this be a preset or something?

**Comment by najdek** [comment]
New update has a reworked popout mode.
It doesn't look like viewing multiple frames in single window is possible anymore.

It's still work-in-progress, but offsets will be configurable from each separate window now.
