### ISSUE TITLE
Automatically position multi-popup windows

### ISSUE THREAD

**Issue by NewsGuyTor** [najdek/f1tv_plus#3]
I think it should be possible to automatically size and position the multi-popup windows. It would be cool if 2 popups  automatically were sized/positioned to take up each half of the screen, and 4 popups each took up one quarter of the screen, without the user manually have to move/position them.

https://developer.mozilla.org/en-US/docs/Web/API/Window/open
https://javascript.info/popup-windows

**Comment by najdek** [comment]
Great idea!
Implemented: https://github.com/najdek/f1tv_plus/commit/60e22540f0c4c3193f3aed26b49f963f7ba67116

**Comment by NewsGuyTor** [comment]
Nice! 

Again, awesome work with the extension! It's already damn near perfect, now it just needs more users!

I'll keep posting ideas when I think of them.
