### ISSUE TITLE
FEATURE: Multi-View - Request for overlay option (display window # & offset)

### ISSUE THREAD

**Issue by SimplyBlu** [najdek/f1tv_plus#32]
In multi-view, would it be possible to add within the Sync menu an overlay option that displays the window # and any offset set for each video feed window?

**Comment by najdek** [comment]
New update has a reworked popout mode.
It doesn't look like viewing multiple frames in single window is possible anymore.

It's still work-in-progress, but offsets will be configurable from each separate window now.
