### ISSUE TITLE
Layout spawning windows not working properly on Firefox

### ISSUE THREAD

**Issue by chrcoluk** [najdek/f1tv_plus#33]
Hi, first thank you for the extension.

Used it for the first time the previous race, and selected the 5 window option with big in the middle and 4 smaller one's.

The first time it failed due to popup blocker, I gave it permission.

Tried it again but it only spawned two windows.  Tried other layouts but only ever two windows spawned, so ended up loading the website three times to get the 5 windows I needed spawned.

Tech details.

Win 10 64bit
Firefox 64bit Latest stable 100.0
Violentmonkey

Please let me know if you need more info on my setup.

**Comment by najdek** [comment]
Violentmonkey is the issue. Looks like it can't open more than one popup from the script (this limit might be intentional).
It works fine with Tampermonkey: https://addons.mozilla.org/en-US/firefox/addon/tampermonkey/
