### ISSUE TITLE
Can you "please" add following layout or add save layout option?

### ISSUE THREAD

**Issue by chrcoluk** [najdek/f1tv_plus#34]
Reason is bigger windows for f1 live and data channel
Four smaller below for chosen onboards.
My scaling is probably off, but I hope the pic gives a good idea.  I can post a screenshot of how I manually did it during race if it helps.

![f1tvlayoutrequest](https://user-images.githubusercontent.com/8260578/169702102-f79e8c46-16e5-42cf-8e05-9f555c8e8081.jpg)

**Comment by najdek** [comment]
Here you can get a version with this layout:
https://github.com/najdek/f1tv_plus/raw/testing/f1tv_plus.user.js

**Comment by chrcoluk** [comment]
Using it now on moanco quali and you nailed it, thank you every much.
