### ISSUE TITLE
all videos going directly to the alt player

### ISSUE THREAD

**Issue by daniec1610** [najdek/f1tv_plus#6]
hi, as the title say. idk if this was intended or not but i sometimes want to have the normal player and since the most recent update (2.0 I believe) all videos default to the alt player and the only way to prevent this is to disable tampermonkey or the script. Was this intended with the newest update or is something wrong on my end?
btw, thanks for this amazing tool!!

**Comment by najdek** [comment]
It's intended behavior.
This player is much more lightweight.
I'll be improving this player. It wasn't really possible to change anything in the default player.
You can get the old version here: https://github.com/najdek/f1tv_plus/raw/v1/f1tv_plus.user.js

**Comment by daniec1610** [comment]
> It's intended behavior.
> This player is much more lightweight.
> I'll be improving this player. It wasn't really possible to change anything in the default player.
> You can get the old version here: https://github.com/najdek/f1tv_plus/raw/v1/f1tv_plus.user.js

thank you for the answer and once again, this tool is great.
